# Generated by Django 4.1.5 on 2023-01-04 11:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('hr', 'hr'), ('project manager', 'project manager'), ('super admin', 'super admin'), ('admin', 'admin'), ('accounts', 'accounts'), ('sales', 'sales'), ('marketing', 'marketing'), ('employee', 'employee')], max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_otp_expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('holiday_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('hours_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('total_hours', models.CharField(max_length=20)),
                ('day_type', models.CharField(choices=[('leave', 'leave'), ('half', 'half'), ('full', 'full')], max_length=10)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('leave_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_leave_id_model_manager', to='leave_app.leavemanagement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_user_id_model_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('permanent_address_line_1', models.TextField()),
                ('permanent_address_line_2', models.TextField(blank=True, null=True)),
                ('permanent_city', models.CharField(max_length=20)),
                ('permanent_state', models.CharField(max_length=20)),
                ('permanent_zipcode', models.CharField(max_length=6)),
                ('current_address_line_1', models.TextField()),
                ('current_address_line_2', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(max_length=20)),
                ('current_state', models.CharField(max_length=20)),
                ('current_zipcode', models.CharField(max_length=6)),
                ('current_country', models.CharField(max_length=20)),
                ('emergency_contact_number_1', models.CharField(max_length=12, null=True)),
                ('emergency_contact_number_2', models.CharField(blank=True, max_length=12, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_user_id_model_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('social_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social_media', models.URLField(blank=True, max_length=20, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile_user_id_model_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision_id', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('revised_On', models.DateField()),
                ('joining_bonus', models.IntegerField()),
                ('basic', models.CharField(max_length=20)),
                ('hra', models.CharField(max_length=20)),
                ('performance', models.CharField(blank=True, max_length=30, null=True)),
                ('itr', models.CharField(max_length=20)),
                ('conveyance_allowance', models.CharField(max_length=20)),
                ('medical_healthcare', models.CharField(max_length=20)),
                ('deduction', models.CharField(max_length=20)),
                ('ctc', models.CharField(max_length=50)),
                ('in_hand', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('others', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_user_id_model_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
