# Generated by Django 4.1.5 on 2023-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiscDocument',
            fields=[
                ('misc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=20)),
                ('document_path', models.URLField()),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('onboarding_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_upload', models.FileField(upload_to='media/onboarding_document/')),
                ('document_name', models.CharField(max_length=30)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
