# Generated by Django 4.1.5 on 2023-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('leave_request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('decided_by', models.CharField(max_length=20)),
                ('decision_comment', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
