# BANKING  INFORMATION  MODEL

BANKING_INFORMATION_FIELD_BANK_ID = 'bank_id'
BANKING_INFORMATION_FIELD_USER_ID = 'user_id'
BANKING_INFORMATION_FIELD_BANK_NAME = 'bank_name'
BANKING_INFORMATION_FIELD_ACCOUNT_NAME = 'account_name'
BANKING_INFORMATION_FIELD_ACCOUNT_NUMBER = 'account_number'
BANKING_INFORMATION_FIELD_IFSC_CODE = 'ifsc_code'
BANKING_INFORMATION_FIELD_CREATED_ON = 'created_on'
BANKING_INFORMATION_FIELD_LAST_MODIFIED = 'last_modified'
BANKING_INFORMATION_FIELD_MODIFIED_BY = 'modified_by'
