# ONBOARDING DOCUMENT MODEL

ONBOARDING_DOCUMENT_FIELD_ONBOARDING_ID = 'onboarding_id'
ONBOARDING_DOCUMENT_FIELD_USER_ID = 'user_id'
ONBOARDING_DOCUMENT_FIELD_DOCUMENT = 'document'
ONBOARDING_DOCUMENT_FIELD_DOCUMENT_NAME = 'document_name'
ONBOARDING_DOCUMENT_FIELD_CREATED_ON = 'created_on'
ONBOARDING_DOCUMENT_FIELD_LAST_MODIFIED_ON = 'last_modified'
ONBOARDING_DOCUMENT_FIELD_MODIFIED_BY_ON = 'modified_by'

# MISC DOCUMENT MODEL

MISC_DOCUMENT_FIELD_MISC_ID = 'misc_id'
MISC_DOCUMENT_FIELD_USER_ID = 'user_id'
MISC_DOCUMENT_FIELD_DOCUMENT_NAME = 'document_name'
MISC_DOCUMENT_FIELD_DOCUMENT_PATH = 'document_path'
MISC_DOCUMENT_FIELD_CREATED_ON = 'created_on'
MISC_DOCUMENT_FIELD_LAST_MODIFIED_ON = 'last_modified'
MISC_DOCUMENT_FIELD_MODIFIED_BY_ON = 'modified_by'
