# Leave Request Model
LEAVE_MANAGEMENT_FIELD_LEAVE_ID = 'leave_id'
LEAVE_MANAGEMENT_FIELD_USER_ID = 'user_id'
LEAVE_MANAGEMENT_FIELD_START_DATE = 'start_date'
LEAVE_MANAGEMENT_FIELD_LAST_DATE = 'end_date'
LEAVE_MANAGEMENT_FIELD_LEAVE_REASON = 'leave_reason'
LEAVE_MANAGEMENT_FIELD_APPROVED = 'approved'
LEAVE_MANAGEMENT_FIELD_DECIDED_BY = 'decided_by'
LEAVE_MANAGEMENT_FIELD_DECISION_COMMENT = 'decision_comment'
LEAVE_MANAGEMENT_FIELD__CREATED_ON = 'created_on'
LEAVE_MANAGEMENT_FIELD_LAST_MODIFIED_ON = 'last_modified'
LEAVE_MANAGEMENT_FIELD_LAST_MODIFIED_BY = 'modified_by'


# LeaveManagement
LEAVE_MANAGEMENT_FIELD_LEAVE_ID = 'leave_id'
LEAVE_MANAGEMENT_FIELD_DATE = 'date'
LEAVE_MANAGEMENT_FIELD_USER_ID = 'user_id'
LEAVE_MANAGEMENT_FIELD_STATUS = 'status'