# User
USER_TYPE_CHOICE_FIELD_HR = 'hr'
USER_TYPE_CHOICE_FIELD_PROJECT_MANAGER = 'project manager'
USER_TYPE_CHOICE_FIELD_SUPER_ADMIN = 'super admin'
USER_TYPE_CHOICE_FIELD_ADMIN = 'admin'
USER_TYPE_CHOICE_FIELD_ACCOUNTS = 'accounts'
USER_TYPE_CHOICE_FIELD_SALES = 'sales'
USER_TYPE_CHOICE_FIELD_MARKETING = 'marketing'
USER_TYPE_CHOICE_FIELD_EMPLOYEE = 'employee'

# Working_Hours
WORKING_HOURS_CHOICE_FIELD_LEAVE = 'leave'
WORKING_HOURS_CHOICE_FIELD_HALF = 'half'
WORKING_HOURS_CHOICE_FIELD_FULL = 'full'

DAY_TYPE = [
    (WORKING_HOURS_CHOICE_FIELD_LEAVE,WORKING_HOURS_CHOICE_FIELD_LEAVE),
    (WORKING_HOURS_CHOICE_FIELD_HALF,WORKING_HOURS_CHOICE_FIELD_HALF),
    (WORKING_HOURS_CHOICE_FIELD_FULL,WORKING_HOURS_CHOICE_FIELD_FULL)

]

USER_ROLL=[

    (USER_TYPE_CHOICE_FIELD_HR,USER_TYPE_CHOICE_FIELD_HR),
    (USER_TYPE_CHOICE_FIELD_PROJECT_MANAGER,USER_TYPE_CHOICE_FIELD_PROJECT_MANAGER),
    (USER_TYPE_CHOICE_FIELD_SUPER_ADMIN,USER_TYPE_CHOICE_FIELD_SUPER_ADMIN),
    (USER_TYPE_CHOICE_FIELD_ADMIN,USER_TYPE_CHOICE_FIELD_ADMIN),
    (USER_TYPE_CHOICE_FIELD_ACCOUNTS,USER_TYPE_CHOICE_FIELD_ACCOUNTS),
    (USER_TYPE_CHOICE_FIELD_SALES,USER_TYPE_CHOICE_FIELD_SALES),
    (USER_TYPE_CHOICE_FIELD_MARKETING,USER_TYPE_CHOICE_FIELD_MARKETING),
    (USER_TYPE_CHOICE_FIELD_EMPLOYEE,USER_TYPE_CHOICE_FIELD_EMPLOYEE)
]

# USER MODEL

USER_FIELD_USER_ID = 'user_id'
USER_FIELD_ROLE = 'role'
USER_FIELD_USERNAME = 'username'
USER_FIELD_FIRST_NAME = 'first_name'
USER_FIELD_LAST_NAME = 'last_name'
USER_FIELD_EMAIL = 'email'
USER_FIELD_PHONE = 'phone'
USER_FIELD_PASSWORD = 'password'
USER_FIELD_PASSWORD2 = 'password2'
USER_FIELD_OTP = 'opt'
USER_FIELD_OTP_EXPIRE = 'otp_expire'
USER_FIELD_CREATED_ON = 'created_on'
USER_FIELD_LAST_MODIFIED = 'last_modified'

# USER_PROFILE MODEL

USER_PROFILE_FIELD_PROFILE_ID = 'profile_id'
USER_PROFILE_FIELD_USER_ID = 'user_id'
USER_PROFILE_FIELD_DATE_OF_BIRTH = 'date_of_birth'
USER_PROFILE_FIELD_PERMANENT_ADDRESS_LINE_1 = 'permanent_address_line_1'
USER_PROFILE_FIELD_PERMANENT_ADDRESS_LINE_2 = 'permanent_address_line_1'
USER_PROFILE_FIELD_PERMANENT_CITY = 'permanent_state'
USER_PROFILE_FIELD_PERMANENT_ZIP_CODE = 'permanent_zipcode'
USER_PROFILE_FIELD_PERMANENT_COUNTRY = 'permanent_country'
USER_PROFILE_FIELD_CURRENT_ADDRESS_LINE_1 = 'current_address_line_1'
USER_PROFILE_FIELD_CURRENT_ADDRESS_LINE_2 = 'current_address_line_2'
USER_PROFILE_FIELD_CURRENT_CITY = 'current_city'
USER_PROFILE_FIELD_CURRENT_STATE = 'current_state'
USER_PROFILE_FIELD_CURRENT_ZIPCODE = 'current_zipcode'
USER_PROFILE_FIELD_CURRENT_COUNTRY = 'current_country'
USER_PROFILE_FIELD_EMERGENCY_CONTACT_NUMBER_1 = 'emergency_contact_number_1'
USER_PROFILE_FIELD_EMERGENCY_CONTACT_NUMBER_2 = 'emergency_contact_number_2'
USER_PROFILE_FIELD_CREATED_ON = 'created_on'
USER_PROFILE_FIELD_LAST_MODIFIED_ON = 'last_modified'
USER_PROFILE_FIELD_MODIFIED_BY = 'modified_by'


# SocialProfile
SOCIAL_PROFILE_FIELD_SOCIAL_PROFILE_ID = 'social_profile_id'
SOCIAL_PROFILE_FIELD_USER_ID = 'user_id'
SOCIAL_PROFILE_FIELD_MODIFIED_BY = 'modified_by'
SOCIAL_PROFILE_FIELD_CREATED_ON = 'created_on'
SOCIAL_PROFILE_FIELD_LAST_MODIFIED_ON = 'last_modified'


# EMPLOYEE SALARY MODEL

EMPLOYEE_SALARY_FIELD_SALARY_ID = 'salary_id'
EMPLOYEE_SALARY_FIELD_USER_ID = 'user_id'
EMPLOYEE_SALARY_FIELD_REVISION_ID = 'revision_id'
EMPLOYEE_SALARY_FIELD_DESIGNATION = 'designation'
EMPLOYEE_SALARY_FIELD_EFFECTIVE_FORM = 'effective_from'
EMPLOYEE_SALARY_FIELD_REVISED_ON = 'revised_On'
EMPLOYEE_SALARY_FIELD_JOINING_ON = 'joining_bonus'
EMPLOYEE_SALARY_FIELD_BASIC = 'basic'
EMPLOYEE_SALARY_FIELD_HRA = 'hra'
EMPLOYEE_SALARY_FIELD_PERFORMANCE = 'performance'
EMPLOYEE_SALARY_FIELD_RETENTION = 'retention'
EMPLOYEE_SALARY_FIELD_ITR = 'itr'
EMPLOYEE_SALARY_FIELD_CONVENIENCE_ALLOWANCE = 'convenience_allowance'
EMPLOYEE_SALARY_FIELD_MEDICAL_HEALTHCARE = 'medical_healthcare'
EMPLOYEE_SALARY_FIELD_DEDUCTION = 'deduction'
EMPLOYEE_SALARY_FIELD_CTC = 'ctc'
EMPLOYEE_SALARY_FIELD_IN_HAND = 'in_hand'
EMPLOYEE_SALARY_FIELD_BONUSES = 'bonuses'
EMPLOYEE_SALARY_FIELD_OTHERS = 'others'
EMPLOYEE_SALARY_FIELD_CREATED_ON = 'created_on'
EMPLOYEE_SALARY_FIELD_LAST_MODIFIED_ON = 'last_modified'
EMPLOYEE_SALARY_FIELD_LAST_MODIFIED_BY = 'modified_by'


# WorkingHours
WORKING_HOURS_FIELD_HOURS_ID = 'hours_id'
WORKING_HOURS_FIELD_USER_ID = 'user_id'
WORKING_HOURS_FIELD_LEAVE_ID = 'leave_id'
WORKING_HOURS_FIELD_FROM_TIME = 'from_time'
WORKING_HOURS_FIELD_TO_TIME = 'to_time'
WORKING_HOURS_FIELD_TOTAL_HOURS = 'total_hours'
WORKING_HOURS_FIELD_DAY_TYPE = 'day_type'
WORKING_HOURS_FIELD_MODIFIED_BY = 'modified_by'
WORKING_HOURS_FIELD_CREATED_ON = 'created_on'
WORKING_HOURS_FIELD_LAST_MODIFIED = 'last_modified'


# PUBLIC HOLIDAY
PUBLIC_HOLIDAY_FIELD_HOLIDAY_ID = 'holiday_id'
PUBLIC_HOLIDAY_FIELD_DATE = 'date'
PUBLIC_HOLIDAY_FIELD_REASON = 'reason'



